### ISSUE TITLE
don't render objects between destination camera and frame

### ISSUE THREAD

**Issue by madblade** [pr0g/unity-portal-rendering#1] opened 2017-01-18 09:27 UTC
Every object that is located between the destination camera and destination portal should be clipped.

A way to do it in opengl:
- Shader-side (GLSL): 
```
uniform vec4 clip;
...
gl_ClipDistance[0] = dot(clip, gl_Vertex);

```
- App-side, communicate  the portal plane as the "clip" uniform.

Thanks!

**Comment by pr0g** [comment] 2017-01-18 20:17
Oh cool! Thank you for this! I'll have a look at updating this at the weekend! 

Cheers!

**Comment by pr0g** [comment] 2017-01-29 13:18
Hello again,

Finally got around to looking at this sorry, forgive me it's been a while since I last looked at this 🤦‍♂️ I'm not sure I can use `gl_ClipDistance` directly in a Unity shader but I can use `clip` in the fragment shader. I understand what to implement but my brain is failing me at visualising what artefact/error this fixes. Could you describe what I would expect to see that's wrong which is fixed by the cliping suggestion you make, or is it purely a performance saving thing?

Forgive me for sounding incredibly foolish, just want to make sure I understand you 100% correctly.

Thanks!


Tom

**Comment by madblade** [comment] 2017-01-29 18:34
Hi again :)

Well it's just to handle this special case:
http://imgur.com/a/Tybma
When you've got an object between a camera portal and the portal frame, you can see the undesirable object being displayed (in my example, in the red circle). That's why I suggested clipping it, unless you have other ideas.

I'm working on it in WebGL but I'm also interested in how it would be done in Unity (given I have little knowledge of the latter).

Thanks!

Max

**Comment by pr0g** [comment] 2017-01-30 08:43
Ah got you! The penny has dropped! :)

Thanks very much for the example! I did a quick test and `clip` looks like it'll do the trick although there may well be a more optimal solution (gl_ClipDistance might be faster I'm not sure I'm afraid) I'll cook something up soon and let you know.

Cheers!


Tom

**Comment by pr0g** [comment] 2017-01-30 23:38
Hello yet again!

Okay been thinking about this - so unfortunately the solution you propose is a bit tricky/annoying to implement in Unity because it means I need to have a custom shader for all normal objects I render that go to the RenderTarget. 

I remembered while looking at the code that the solution I'd messed around with was adjusting the portal cameras near clip plane (it's commented out in PortalCamera.cs with a hack fudge factor) this solves the issue you mentioned but causes other horrible artefacts because the near clip plane is not coplanar with the portal. However! There is a technique called Oblique View Frustums which solves this issue, I was just too lazy to implement it before. I'll look at adding it soon though and it should fix the problem you observed!

Thanks again!


Tom

**Comment by madblade** [comment] 2017-01-31 10:40
Hi!
Thank you for investigating!

You're quite right about having custom shaders for every object, that's not clean.
It seems like a better idea to play with the camera clipping planes.

Now in WebGL there's the possibility of attaching global clipping planes to a renderer, but again...
I need to switch between clipping planes every time I render from a different camera, or use multiple renderers...

Looking forward to seeing your Oblique View Frustums solution :)

Thanks!

**Comment by pr0g** [comment] 2017-01-31 23:50
Hey!

I nearly have a fix! 😄 

Turns out Unity already has a handy CalculateObliqueMatrix function I didn't know about! It's described here (http://aras-p.info/texts/obliqueortho.html)

I'm using that now and it solves the issue you describe - there's one odd thing I want to fix before I push my changes (some weird clipping thing on one of the cameras, I think it might be a Scene/Data thing my end) Once that's fixed I'll update and you can take a look!

Thank you for your patience! 😁 

Might not be able to get to it until Thursday now though sorry!

Cheers!


Tom

**Comment by pr0g** [comment] 2017-02-03 09:14
Finally updated!! 😄 

Fixed a bunch of stuff in the scene I was doing that was stupid and have the new oblique matrix stuff working! All much more sensible and better now! Thank you very much for bringing this to my attention!

Also interesting aside, when transforming planes/normals you can't just transform them like a normal vector (I'd forgotten this 🤦‍♂️ ) This is a really good explanation! - http://computergraphics.stackexchange.com/questions/1502/why-is-the-transposed-inverse-of-the-model-view-matrix-used-to-transform-the-nor

Grab latest and let me know if anything seems wrong!

Cheers!


Tom

**Closed as completed by pr0g** 2017-02-03 09:14 UTC

**Comment by madblade** [comment] 2017-02-03 12:50
Awesome! Works like a charm.
Thanks again for your links (and tutorial btw), that helps! 

See you!

**Comment by pr0g** [comment] 2017-02-04 13:51
Hey again,

I do realise I'm cheating a bit with the symmetry of the scene - I am going to update it so it handles arbitrary orientations of the portals properly (I'll need to add back in a second camera to the main scene - so a camera per portal).

I'll hopefully update it soon! Cheers!

**Comment by pr0g** [comment] 2017-02-04 20:07
Updated the Portal.cs script and scene to work more nicely now - the transforms of each Portal are now the same, and in the script, it flips the corresponding one 180 degrees so the camera appears in the correct orientation (roughly speaking the portal camera is a mirror image of the main camera)

Cheers!

**Comment by madblade** [comment] 2017-02-04 22:26
Thanks yet again!
Updating asap. Portals are indeed a fascinating subject ;) but sometimes they give me headaches...

**Comment by pr0g** [comment] 2017-02-05 14:08
No worries! Haha me too!

Before I had the CentreTransform of the two portals in the scene being the mirror of one another, so one had local z pointing out of the portal, and the other had local z pointing in. This was so when putting the portal camera in the space of the destination portal, it would appear in the correct place. The problem is as I was using the forward vector of the destination portal to create the plane for the ObliqueProjectionMatrix, it was pointing the wrong way in one case, so the distance from the plane calculation was wrong. Now the CentreTransform for each portal surface is always facing out of the portal and in Portal.cs, I rotate the transform 180 degrees about the local up transform.

Just fixed another tiny bug with how I was calculating the rotation - justed tested with lots of mad orientations and all seemed good! Finally! :)

Thanks again!
