### ISSUE TITLE
RenderTexture Distorted in iPhone landscape mode.

### ISSUE THREAD

**Issue by godzil21** [pr0g/unity-portal-rendering#3] opened 2017-09-18 13:13 UTC
When trying this awesome demo in my iPhone in landscape mode the render texture inside the portal appears distorted before entering inside the Portal…

Can this be fixed? Thanks a lot.

**Comment by pr0g** [comment] 2017-09-19 21:42
Hey there, this appears to be related to the previous issue. I'm in the process of trying to repro, likely seems something to do with the aspect ratio, I'm likely doing something stupid, should hopefully have an update tomorrow.

Cheers!

**Comment by pr0g** [comment] 2019-01-28 22:23
Hey there,

A rather late update sorry 😬 I have been able to get the demo running on my iPad but was not able to reproduce the issue (using Unity 2018.3.2f1). The portals do appear to render correctly in portrait and landscape.

I've added camera controls for movement on device (mobile/tablet) to make things a bit easier to test, let me know if things still aren't working if you try it again,

Closing for now,

Cheers

**Closed as completed by pr0g** 2019-01-28 22:23 UTC
